### ISSUE TITLE
Reading from a blob takes to much time

### ISSUE THREAD

**Issue by hadiidbouk** [Microsoft/appcenter-sample-export#4]
let say that I want all the logs before 1 year, this sample app will try to access all the possible directory for  months [1,12] then it will try to access all the possible directories for days [1,31] then every possible minute [1,59].

In a simple calculation, if accessing a directory will takes 1 sec and reading from a file (inside the minute directory) will takes 4 sec. then to get all the logs before 1 year will takes 
 (12+ 31)+ (59*4) = 451 seconds = 7.51667 minutes.

let's says I am using this into my API, the user should wait for 7.51667 minutes to get his logs ( without counting the time needed to format the API).

**Comment by pshrosbree** [comment]
The point of the samples is to show how you can retrieve your data using export and write it elsewhere. How you store it is up to you, and you should read it and store it in a format that suits your purposes. The format it is stored in by export is especially not for suitable rapid or frequent access. The samples do not try to address your scenarios but do provide code from which you can implement approaches suitable for your scenarios.
